/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as databaseSol from "./Database.sol";
export type { databaseSol };
import type * as spreadLoveSol from "./SpreadLove.sol";
export type { spreadLoveSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DSD } from "./DSD";
