/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IDatabase, IDatabaseInterface } from "../../Lock.sol/IDatabase";

const _abi = [
  {
    inputs: [],
    name: "first",
    outputs: [
      {
        internalType: "address",
        name: "un",
        type: "address",
      },
      {
        internalType: "address",
        name: "deux",
        type: "address",
      },
      {
        internalType: "address",
        name: "trois",
        type: "address",
      },
      {
        internalType: "address",
        name: "quattre",
        type: "address",
      },
      {
        internalType: "address",
        name: "cinq",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "second",
    outputs: [
      {
        internalType: "address",
        name: "un",
        type: "address",
      },
      {
        internalType: "address",
        name: "deux",
        type: "address",
      },
      {
        internalType: "address",
        name: "trois",
        type: "address",
      },
      {
        internalType: "address",
        name: "quattre",
        type: "address",
      },
      {
        internalType: "address",
        name: "cinq",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDatabase__factory {
  static readonly abi = _abi;
  static createInterface(): IDatabaseInterface {
    return new utils.Interface(_abi) as IDatabaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDatabase {
    return new Contract(address, _abi, signerOrProvider) as IDatabase;
  }
}
