/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDatabase__factory } from "./IDatabase__factory";
export { SpreadLove__factory } from "./SpreadLove__factory";
