/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface SpreadLoveInterface extends utils.Interface {
  functions: {
    "database()": FunctionFragment;
    "getShares()": FunctionFragment;
    "getTotalShare()": FunctionFragment;
    "spreadLuv()": FunctionFragment;
    "spreadMoney(address)": FunctionFragment;
    "viewAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "database"
      | "getShares"
      | "getTotalShare"
      | "spreadLuv"
      | "spreadMoney"
      | "viewAddress"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "database", values?: undefined): string;
  encodeFunctionData(functionFragment: "getShares", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTotalShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "spreadLuv", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "spreadMoney",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "viewAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "database", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spreadLuv", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spreadMoney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SpreadLove extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpreadLoveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    database(overrides?: CallOverrides): Promise<[string]>;

    getShares(overrides?: CallOverrides): Promise<[number[]]>;

    getTotalShare(overrides?: CallOverrides): Promise<[number[]]>;

    spreadLuv(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    spreadMoney(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    viewAddress(overrides?: CallOverrides): Promise<[string[]]>;
  };

  database(overrides?: CallOverrides): Promise<string>;

  getShares(overrides?: CallOverrides): Promise<number[]>;

  getTotalShare(overrides?: CallOverrides): Promise<number[]>;

  spreadLuv(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  spreadMoney(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  viewAddress(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    database(overrides?: CallOverrides): Promise<string>;

    getShares(overrides?: CallOverrides): Promise<number[]>;

    getTotalShare(overrides?: CallOverrides): Promise<number[]>;

    spreadLuv(overrides?: CallOverrides): Promise<void>;

    spreadMoney(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    viewAddress(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    database(overrides?: CallOverrides): Promise<BigNumber>;

    getShares(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalShare(overrides?: CallOverrides): Promise<BigNumber>;

    spreadLuv(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    spreadMoney(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    viewAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    database(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalShare(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    spreadLuv(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    spreadMoney(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    viewAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
