/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDatabase } from "./IDatabase";
export type { IERC20 } from "./IERC20";
export type { SpreadLove } from "./SpreadLove";
