/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SpreadLoveInterface extends utils.Interface {
  functions: {
    "database()": FunctionFragment;
    "disperseEther(address[],uint256[])": FunctionFragment;
    "disperseToken(address,address[],uint256[])": FunctionFragment;
    "disperseTokenSimple(address,address[],uint256[])": FunctionFragment;
    "first()": FunctionFragment;
    "second()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "database"
      | "disperseEther"
      | "disperseToken"
      | "disperseTokenSimple"
      | "first"
      | "second"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "database", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disperseEther",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseTokenSimple",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "first", values?: undefined): string;
  encodeFunctionData(functionFragment: "second", values?: undefined): string;

  decodeFunctionResult(functionFragment: "database", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disperseEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseTokenSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "first", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "second", data: BytesLike): Result;

  events: {};
}

export interface SpreadLove extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SpreadLoveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    database(overrides?: CallOverrides): Promise<[string]>;

    disperseEther(
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disperseToken(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disperseTokenSimple(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    first(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        un: string;
        deux: string;
        trois: string;
        quattre: string;
        cinq: string;
      }
    >;

    second(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        un: string;
        deux: string;
        trois: string;
        quattre: string;
        cinq: string;
      }
    >;
  };

  database(overrides?: CallOverrides): Promise<string>;

  disperseEther(
    recipients: PromiseOrValue<string>[],
    values: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disperseToken(
    token: PromiseOrValue<string>,
    recipients: PromiseOrValue<string>[],
    values: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disperseTokenSimple(
    token: PromiseOrValue<string>,
    recipients: PromiseOrValue<string>[],
    values: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  first(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string] & {
      un: string;
      deux: string;
      trois: string;
      quattre: string;
      cinq: string;
    }
  >;

  second(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string] & {
      un: string;
      deux: string;
      trois: string;
      quattre: string;
      cinq: string;
    }
  >;

  callStatic: {
    database(overrides?: CallOverrides): Promise<string>;

    disperseEther(
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    disperseToken(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    disperseTokenSimple(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    first(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        un: string;
        deux: string;
        trois: string;
        quattre: string;
        cinq: string;
      }
    >;

    second(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        un: string;
        deux: string;
        trois: string;
        quattre: string;
        cinq: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    database(overrides?: CallOverrides): Promise<BigNumber>;

    disperseEther(
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disperseToken(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disperseTokenSimple(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    first(overrides?: CallOverrides): Promise<BigNumber>;

    second(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    database(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disperseEther(
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disperseToken(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disperseTokenSimple(
      token: PromiseOrValue<string>,
      recipients: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    first(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    second(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
