/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface DataBaseInterface extends utils.Interface {
  functions: {
    "getAddressBook()": FunctionFragment;
    "getBal(address)": FunctionFragment;
    "getShares()": FunctionFragment;
    "setArrays(bytes,bytes)": FunctionFragment;
    "setBackup(address)": FunctionFragment;
    "totalShares()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getAddressBook"
      | "getBal"
      | "getShares"
      | "setArrays"
      | "setBackup"
      | "totalShares"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAddressBook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBal",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getShares", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setArrays",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackup",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAddressBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setArrays", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBackup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DataBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DataBaseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAddressBook(overrides?: CallOverrides): Promise<[string[]]>;

    getBal(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getShares(overrides?: CallOverrides): Promise<[number[]]>;

    setArrays(
      targets: PromiseOrValue<BytesLike>,
      byteShares: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBackup(
      _backup: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getAddressBook(overrides?: CallOverrides): Promise<string[]>;

  getBal(
    who: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getShares(overrides?: CallOverrides): Promise<number[]>;

  setArrays(
    targets: PromiseOrValue<BytesLike>,
    byteShares: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBackup(
    _backup: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getAddressBook(overrides?: CallOverrides): Promise<string[]>;

    getBal(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShares(overrides?: CallOverrides): Promise<number[]>;

    setArrays(
      targets: PromiseOrValue<BytesLike>,
      byteShares: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBackup(
      _backup: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getAddressBook(overrides?: CallOverrides): Promise<BigNumber>;

    getBal(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShares(overrides?: CallOverrides): Promise<BigNumber>;

    setArrays(
      targets: PromiseOrValue<BytesLike>,
      byteShares: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBackup(
      _backup: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAddressBook(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBal(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setArrays(
      targets: PromiseOrValue<BytesLike>,
      byteShares: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBackup(
      _backup: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
