/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "DataBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DataBase__factory>;
    getContractFactory(
      name: "DSD",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DSD__factory>;
    getContractFactory(
      name: "IERC20BurnableMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20BurnableMinter__factory>;
    getContractFactory(
      name: "IDatabase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDatabase__factory>;
    getContractFactory(
      name: "SpreadLove",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SpreadLove__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "DataBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DataBase>;
    getContractAt(
      name: "DSD",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DSD>;
    getContractAt(
      name: "IERC20BurnableMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20BurnableMinter>;
    getContractAt(
      name: "IDatabase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDatabase>;
    getContractAt(
      name: "SpreadLove",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SpreadLove>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
